### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by negari** [kalintsenkov/BlazorShop#4]
Hi, 

While running blazorshop in my local, I'm getting this error in the browser:
DevTools failed to load SourceMap: Could not load content for .../js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

tested with Chrome and microsoft Edge

**Comment by kalintsenkov** [comment]
Hi,

I think that I fixed the problem! 🙂

Clone repo, clear site data and run the project again. Let me know if the problem persists. 🙂

**Comment by negari** [comment]
it's fixed now, thanks
