### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by thalaeg** [kalintsenkov/BlazorShop#5]
I tried to follow the direction in the README.md, however, I get the following error when trying that.
![image](https://user-images.githubusercontent.com/21165278/99593532-6b3f5a00-29b7-11eb-9332-7f8c87bee5a6.png)

I then loaded up the project in visual studio, set the BlazorShop.Web.Client to the startup project and booted up IIS and again got an error.
![image](https://user-images.githubusercontent.com/21165278/99593681-ab9ed800-29b7-11eb-9cef-be92129ad7f6.png)
Which then outputted the following error.
![image](https://user-images.githubusercontent.com/21165278/99593761-cc672d80-29b7-11eb-9eb5-06784d534ddf.png)

I have .NET 5 SDK

**Comment by kalintsenkov** [comment]
@thalaeg I think that you need to install .NET Core 3.1 SDK

**Comment by thalaeg** [comment]
Okay. So I probably just need to specify .NET Core 3.1 sdk (cause it is probably defaulting to .NET 5).

**Comment by kalintsenkov** [comment]
@thalaeg Install .NET Core 3.1 sdk and let me know if thе problem persists 🙂

**Comment by kalintsenkov** [comment]
@thalaeg  I updated the README.md file. You can now run the project from the command prompt 🙂
