### ISSUE TITLE
the way in readme cannot run the application

### ISSUE THREAD

**Issue by LeiYangGH** [kalintsenkov/BlazorShop#6]
`dotnet` says cannot find the project to run.
even cd into `src` folder reports the same error.

**Comment by kalintsenkov** [comment]
@LeiYangGH Try to run it in Visual Studio and make sure that Client is set as startup project

**Comment by LeiYangGH** [comment]
what about server? can i run client alone?

**Comment by kalintsenkov** [comment]
@LeiYangGH Sorry, I meant Server. My bad.

**Comment by kalintsenkov** [comment]
@LeiYangGH I updated the README.md file. You can now run the project from the command prompt 🙂

**Comment by LeiYangGH** [comment]
thanks. this command works for me. and the site looks great!
it's very kind of you to update the readme.
i'll close the issue.
