### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by zoltanhalasz** [kalintsenkov/BlazorShop#9]
user is: admin@blazorshop.com
but what's the password?
I would like to see the admin dashboard.

Zoltan

**Comment by kalintsenkov** [comment]
Hello,

Here you can find the password: https://github.com/kalintsenkov/BlazorShop/blob/67ce8694358526cc8e46a3167b040035f610ead0/src/BlazorShop.Data/BlazorShopDbInitializer.cs#L82 🙂
For now, the admin only can add, update and delete products. Maybe in the future, I will add an admin dashboard 🙂
